/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationApplicationSyncWindowsResponse {
    #[serde(rename = "activeWindows", skip_serializing_if = "Option::is_none")]
    pub active_windows: Option<Vec<models::ApplicationApplicationSyncWindow>>,
    #[serde(rename = "assignedWindows", skip_serializing_if = "Option::is_none")]
    pub assigned_windows: Option<Vec<models::ApplicationApplicationSyncWindow>>,
    #[serde(rename = "canSync", skip_serializing_if = "Option::is_none")]
    pub can_sync: Option<bool>,
}

impl ApplicationApplicationSyncWindowsResponse {
    pub fn new() -> ApplicationApplicationSyncWindowsResponse {
        ApplicationApplicationSyncWindowsResponse {
            active_windows: None,
            assigned_windows: None,
            can_sync: None,
        }
    }
}
