/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationsetApplicationSetResponse {
    #[serde(rename = "applicationset", skip_serializing_if = "Option::is_none")]
    pub applicationset: Option<Box<models::V1alpha1ApplicationSet>>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
}

impl ApplicationsetApplicationSetResponse {
    pub fn new() -> ApplicationsetApplicationSetResponse {
        ApplicationsetApplicationSetResponse {
            applicationset: None,
            project: None,
        }
    }
}
