/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationFileChunk {
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "chunk", skip_serializing_if = "Option::is_none")]
    pub chunk: Option<Vec<u8>>,
}

impl ApplicationFileChunk {
    pub fn new() -> ApplicationFileChunk {
        ApplicationFileChunk { chunk: None }
    }
}
