/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationApplicationManifestQueryWithFiles {
    #[serde(rename = "appNamespace", skip_serializing_if = "Option::is_none")]
    pub app_namespace: Option<String>,
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
}

impl ApplicationApplicationManifestQueryWithFiles {
    pub fn new() -> ApplicationApplicationManifestQueryWithFiles {
        ApplicationApplicationManifestQueryWithFiles {
            app_namespace: None,
            checksum: None,
            name: None,
            project: None,
        }
    }
}

