/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationResourceActionRunRequestV2 {
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(rename = "appNamespace", skip_serializing_if = "Option::is_none")]
    pub app_namespace: Option<String>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(
        rename = "resourceActionParameters",
        skip_serializing_if = "Option::is_none"
    )]
    pub resource_action_parameters: Option<Vec<models::ApplicationResourceActionParameters>>,
    #[serde(rename = "resourceName", skip_serializing_if = "Option::is_none")]
    pub resource_name: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl ApplicationResourceActionRunRequestV2 {
    pub fn new() -> ApplicationResourceActionRunRequestV2 {
        ApplicationResourceActionRunRequestV2 {
            action: None,
            app_namespace: None,
            group: None,
            kind: None,
            name: None,
            namespace: None,
            project: None,
            resource_action_parameters: None,
            resource_name: None,
            version: None,
        }
    }
}
