/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationsetApplicationSetGenerateResponse {
    #[serde(rename = "applications", skip_serializing_if = "Option::is_none")]
    pub applications: Option<Vec<models::V1alpha1Application>>,
}

impl ApplicationsetApplicationSetGenerateResponse {
    pub fn new() -> ApplicationsetApplicationSetGenerateResponse {
        ApplicationsetApplicationSetGenerateResponse {
            applications: None,
        }
    }
}

