/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationResourceActionsListResponse {
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<Vec<models::V1alpha1ResourceAction>>,
}

impl ApplicationResourceActionsListResponse {
    pub fn new() -> ApplicationResourceActionsListResponse {
        ApplicationResourceActionsListResponse { actions: None }
    }
}
