/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationsetApplicationSetGenerateRequest {
    #[serde(rename = "applicationSet", skip_serializing_if = "Option::is_none")]
    pub application_set: Option<Box<models::V1alpha1ApplicationSet>>,
}

impl ApplicationsetApplicationSetGenerateRequest {
    pub fn new() -> ApplicationsetApplicationSetGenerateRequest {
        ApplicationsetApplicationSetGenerateRequest {
            application_set: None,
        }
    }
}

