/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationApplicationSyncWindow {
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<String>,
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "manualSync", skip_serializing_if = "Option::is_none")]
    pub manual_sync: Option<bool>,
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<String>,
}

impl ApplicationApplicationSyncWindow {
    pub fn new() -> ApplicationApplicationSyncWindow {
        ApplicationApplicationSyncWindow {
            duration: None,
            kind: None,
            manual_sync: None,
            schedule: None,
        }
    }
}
