/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationApplicationResourceResponse {
    #[serde(rename = "manifest", skip_serializing_if = "Option::is_none")]
    pub manifest: Option<String>,
}

impl ApplicationApplicationResourceResponse {
    pub fn new() -> ApplicationApplicationResourceResponse {
        ApplicationApplicationResourceResponse {
            manifest: None,
        }
    }
}

