/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationApplicationManifestQueryWithFilesWrapper {
    #[serde(rename = "chunk", skip_serializing_if = "Option::is_none")]
    pub chunk: Option<Box<models::ApplicationFileChunk>>,
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Box<models::ApplicationApplicationManifestQueryWithFiles>>,
}

impl ApplicationApplicationManifestQueryWithFilesWrapper {
    pub fn new() -> ApplicationApplicationManifestQueryWithFilesWrapper {
        ApplicationApplicationManifestQueryWithFilesWrapper {
            chunk: None,
            query: None,
        }
    }
}

