/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterHelp {
    #[serde(rename = "binaryUrls", skip_serializing_if = "Option::is_none")]
    pub binary_urls: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "chatText", skip_serializing_if = "Option::is_none")]
    pub chat_text: Option<String>,
    #[serde(rename = "chatUrl", skip_serializing_if = "Option::is_none")]
    pub chat_url: Option<String>,
}

impl ClusterHelp {
    pub fn new() -> ClusterHelp {
        ClusterHelp {
            binary_urls: None,
            chat_text: None,
            chat_url: None,
        }
    }
}
