/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterGoogleAnalyticsConfig {
    #[serde(rename = "anonymizeUsers", skip_serializing_if = "Option::is_none")]
    pub anonymize_users: Option<bool>,
    #[serde(rename = "trackingID", skip_serializing_if = "Option::is_none")]
    pub tracking_id: Option<String>,
}

impl ClusterGoogleAnalyticsConfig {
    pub fn new() -> ClusterGoogleAnalyticsConfig {
        ClusterGoogleAnalyticsConfig {
            anonymize_users: None,
            tracking_id: None,
        }
    }
}

