/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterSettingsPluginsResponse {
    #[serde(rename = "plugins", skip_serializing_if = "Option::is_none")]
    pub plugins: Option<Vec<models::ClusterPlugin>>,
}

impl ClusterSettingsPluginsResponse {
    pub fn new() -> ClusterSettingsPluginsResponse {
        ClusterSettingsPluginsResponse {
            plugins: None,
        }
    }
}

