/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GpgkeyGnuPgPublicKeyCreateResponse {
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<Box<models::V1alpha1GnuPgPublicKeyList>>,
    #[serde(rename = "skipped", skip_serializing_if = "Option::is_none")]
    pub skipped: Option<Vec<String>>,
}

impl GpgkeyGnuPgPublicKeyCreateResponse {
    pub fn new() -> GpgkeyGnuPgPublicKeyCreateResponse {
        GpgkeyGnuPgPublicKeyCreateResponse {
            created: None,
            skipped: None,
        }
    }
}

