/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IntstrIntOrString : +protobuf=true +protobuf.options.(gogoproto.goproto_stringer)=false +k8s:openapi-gen=true
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntstrIntOrString {
    #[serde(rename = "intVal", skip_serializing_if = "Option::is_none")]
    pub int_val: Option<i32>,
    #[serde(rename = "strVal", skip_serializing_if = "Option::is_none")]
    pub str_val: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i64>,
}

impl IntstrIntOrString {
    /// +protobuf=true +protobuf.options.(gogoproto.goproto_stringer)=false +k8s:openapi-gen=true
    pub fn new() -> IntstrIntOrString {
        IntstrIntOrString {
            int_val: None,
            str_val: None,
            r#type: None,
        }
    }
}

