/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OidcClaim {
    #[serde(rename = "essential", skip_serializing_if = "Option::is_none")]
    pub essential: Option<bool>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

impl OidcClaim {
    pub fn new() -> OidcClaim {
        OidcClaim {
            essential: None,
            value: None,
            values: None,
        }
    }
}
