/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectProjectCreateRequest : ProjectCreateRequest defines project creation parameters.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectProjectCreateRequest {
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::V1alpha1AppProject>>,
    #[serde(rename = "upsert", skip_serializing_if = "Option::is_none")]
    pub upsert: Option<bool>,
}

impl ProjectProjectCreateRequest {
    /// ProjectCreateRequest defines project creation parameters.
    pub fn new() -> ProjectProjectCreateRequest {
        ProjectProjectCreateRequest {
            project: None,
            upsert: None,
        }
    }
}
