/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectProjectTokenResponse : ProjectTokenResponse wraps the created token or returns an empty string if deleted.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectProjectTokenResponse {
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl ProjectProjectTokenResponse {
    /// ProjectTokenResponse wraps the created token or returns an empty string if deleted.
    pub fn new() -> ProjectProjectTokenResponse {
        ProjectProjectTokenResponse {
            token: None,
        }
    }
}

