/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectProjectUpdateRequest {
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::V1alpha1AppProject>>,
}

impl ProjectProjectUpdateRequest {
    pub fn new() -> ProjectProjectUpdateRequest {
        ProjectProjectUpdateRequest {
            project: None,
        }
    }
}

