/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectSyncWindowsResponse {
    #[serde(rename = "windows", skip_serializing_if = "Option::is_none")]
    pub windows: Option<Vec<models::V1alpha1SyncWindow>>,
}

impl ProjectSyncWindowsResponse {
    pub fn new() -> ProjectSyncWindowsResponse {
        ProjectSyncWindowsResponse { windows: None }
    }
}
