/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryPluginAppSpec {
    #[serde(rename = "parametersAnnouncement", skip_serializing_if = "Option::is_none")]
    pub parameters_announcement: Option<Vec<models::RepositoryParameterAnnouncement>>,
}

impl RepositoryPluginAppSpec {
    pub fn new() -> RepositoryPluginAppSpec {
        RepositoryPluginAppSpec {
            parameters_announcement: None,
        }
    }
}

