/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SessionSessionCreateRequest : SessionCreateRequest is for logging in.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionSessionCreateRequest {
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl SessionSessionCreateRequest {
    /// SessionCreateRequest is for logging in.
    pub fn new() -> SessionSessionCreateRequest {
        SessionSessionCreateRequest {
            password: None,
            token: None,
            username: None,
        }
    }
}
