/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1EventSource : EventSource contains information for an event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1EventSource {
    #[serde(rename = "component", skip_serializing_if = "Option::is_none")]
    pub component: Option<String>,
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
}

impl V1EventSource {
    /// EventSource contains information for an event.
    pub fn new() -> V1EventSource {
        V1EventSource {
            component: None,
            host: None,
        }
    }
}

