/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1GroupKind : +protobuf.options.(gogoproto.goproto_stringer)=false
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GroupKind {
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
}

impl V1GroupKind {
    /// +protobuf.options.(gogoproto.goproto_stringer)=false
    pub fn new() -> V1GroupKind {
        V1GroupKind {
            group: None,
            kind: None,
        }
    }
}
