/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1ListMeta : ListMeta describes metadata that synthetic resources must have, including lists and various status objects. A resource may have only one of {ObjectMeta, ListMeta}.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListMeta {
    /// continue may be set if the user set a limit on the number of items returned, and indicates that the server has more data available. The value is opaque and may be used to issue another request to the endpoint that served this list to retrieve the next set of available objects. Continuing a consistent list may not be possible if the server configuration has changed or more than a few minutes have passed. The resourceVersion field returned when using this continue value will be identical to the value in the first response, unless you have received this token from an error message.
    #[serde(rename = "continue", skip_serializing_if = "Option::is_none")]
    pub r#continue: Option<String>,
    #[serde(rename = "remainingItemCount", skip_serializing_if = "Option::is_none")]
    pub remaining_item_count: Option<i64>,
    #[serde(rename = "resourceVersion", skip_serializing_if = "Option::is_none")]
    pub resource_version: Option<String>,
    #[serde(rename = "selfLink", skip_serializing_if = "Option::is_none")]
    pub self_link: Option<String>,
}

impl V1ListMeta {
    /// ListMeta describes metadata that synthetic resources must have, including lists and various status objects. A resource may have only one of {ObjectMeta, ListMeta}.
    pub fn new() -> V1ListMeta {
        V1ListMeta {
            r#continue: None,
            remaining_item_count: None,
            resource_version: None,
            self_link: None,
        }
    }
}

