/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1LabelSelectorRequirement : A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1LabelSelectorRequirement {
    /// key is the label key that the selector applies to.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<String>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

impl V1LabelSelectorRequirement {
    /// A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
    pub fn new() -> V1LabelSelectorRequirement {
        V1LabelSelectorRequirement {
            key: None,
            operator: None,
            values: None,
        }
    }
}

