/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1LabelSelector {
    #[serde(rename = "matchExpressions", skip_serializing_if = "Option::is_none")]
    pub match_expressions: Option<Vec<models::V1LabelSelectorRequirement>>,
    #[serde(rename = "matchLabels", skip_serializing_if = "Option::is_none")]
    pub match_labels: Option<std::collections::HashMap<String, String>>,
}

impl V1LabelSelector {
    pub fn new() -> V1LabelSelector {
        V1LabelSelector {
            match_expressions: None,
            match_labels: None,
        }
    }
}
