/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1NodeSwapStatus : NodeSwapStatus represents swap memory information.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1NodeSwapStatus {
    #[serde(rename = "capacity", skip_serializing_if = "Option::is_none")]
    pub capacity: Option<i64>,
}

impl V1NodeSwapStatus {
    /// NodeSwapStatus represents swap memory information.
    pub fn new() -> V1NodeSwapStatus {
        V1NodeSwapStatus {
            capacity: None,
        }
    }
}

