/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1PullRequestGenerator : PullRequestGenerator defines a generator that scrapes a PullRequest API to find candidate pull requests.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1PullRequestGenerator {
    #[serde(rename = "azuredevops", skip_serializing_if = "Option::is_none")]
    pub azuredevops: Option<Box<models::V1alpha1PullRequestGeneratorAzureDevOps>>,
    #[serde(rename = "bitbucket", skip_serializing_if = "Option::is_none")]
    pub bitbucket: Option<Box<models::V1alpha1PullRequestGeneratorBitbucket>>,
    #[serde(rename = "bitbucketServer", skip_serializing_if = "Option::is_none")]
    pub bitbucket_server: Option<Box<models::V1alpha1PullRequestGeneratorBitbucketServer>>,
    /// Filters for which pull requests should be considered.
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<models::V1alpha1PullRequestGeneratorFilter>>,
    #[serde(rename = "gitea", skip_serializing_if = "Option::is_none")]
    pub gitea: Option<Box<models::V1alpha1PullRequestGeneratorGitea>>,
    #[serde(rename = "github", skip_serializing_if = "Option::is_none")]
    pub github: Option<Box<models::V1alpha1PullRequestGeneratorGithub>>,
    #[serde(rename = "gitlab", skip_serializing_if = "Option::is_none")]
    pub gitlab: Option<Box<models::V1alpha1PullRequestGeneratorGitLab>>,
    /// Standard parameters.
    #[serde(
        rename = "requeueAfterSeconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub requeue_after_seconds: Option<i64>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Box<models::V1alpha1ApplicationSetTemplate>>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<std::collections::HashMap<String, String>>,
}

impl V1alpha1PullRequestGenerator {
    /// PullRequestGenerator defines a generator that scrapes a PullRequest API to find candidate pull requests.
    pub fn new() -> V1alpha1PullRequestGenerator {
        V1alpha1PullRequestGenerator {
            azuredevops: None,
            bitbucket: None,
            bitbucket_server: None,
            filters: None,
            gitea: None,
            github: None,
            gitlab: None,
            requeue_after_seconds: None,
            template: None,
            values: None,
        }
    }
}
