/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1ResourceIgnoreDifferences : ResourceIgnoreDifferences contains resource filter and list of json paths which should be ignored during comparison with live state.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ResourceIgnoreDifferences {
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    #[serde(rename = "jqPathExpressions", skip_serializing_if = "Option::is_none")]
    pub jq_path_expressions: Option<Vec<String>>,
    #[serde(rename = "jsonPointers", skip_serializing_if = "Option::is_none")]
    pub json_pointers: Option<Vec<String>>,
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "managedFieldsManagers", skip_serializing_if = "Option::is_none")]
    pub managed_fields_managers: Option<Vec<String>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

impl V1alpha1ResourceIgnoreDifferences {
    /// ResourceIgnoreDifferences contains resource filter and list of json paths which should be ignored during comparison with live state.
    pub fn new() -> V1alpha1ResourceIgnoreDifferences {
        V1alpha1ResourceIgnoreDifferences {
            group: None,
            jq_path_expressions: None,
            json_pointers: None,
            kind: None,
            managed_fields_managers: None,
            name: None,
            namespace: None,
        }
    }
}

