/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1ScmProviderGeneratorBitbucket : SCMProviderGeneratorBitbucket defines connection info specific to Bitbucket Cloud (API version 2).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ScmProviderGeneratorBitbucket {
    /// Scan all branches instead of just the main branch.
    #[serde(rename = "allBranches", skip_serializing_if = "Option::is_none")]
    pub all_branches: Option<bool>,
    #[serde(rename = "appPasswordRef", skip_serializing_if = "Option::is_none")]
    pub app_password_ref: Option<Box<models::V1alpha1SecretRef>>,
    /// Bitbucket workspace to scan. Required.
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
}

impl V1alpha1ScmProviderGeneratorBitbucket {
    /// SCMProviderGeneratorBitbucket defines connection info specific to Bitbucket Cloud (API version 2).
    pub fn new() -> V1alpha1ScmProviderGeneratorBitbucket {
        V1alpha1ScmProviderGeneratorBitbucket {
            all_branches: None,
            app_password_ref: None,
            owner: None,
            user: None,
        }
    }
}

