/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ConfigManagementPlugin {
    #[serde(rename = "generate", skip_serializing_if = "Option::is_none")]
    pub generate: Option<Box<models::V1alpha1Command>>,
    #[serde(rename = "init", skip_serializing_if = "Option::is_none")]
    pub init: Option<Box<models::V1alpha1Command>>,
    #[serde(rename = "lockRepo", skip_serializing_if = "Option::is_none")]
    pub lock_repo: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl V1alpha1ConfigManagementPlugin {
    pub fn new() -> V1alpha1ConfigManagementPlugin {
        V1alpha1ConfigManagementPlugin {
            generate: None,
            init: None,
            lock_repo: None,
            name: None,
        }
    }
}
