/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1ResourceNetworkingInfo : ResourceNetworkingInfo holds networking-related information for a resource.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ResourceNetworkingInfo {
    /// ExternalURLs holds a list of URLs that should be accessible externally. This field is typically populated for Ingress resources based on their hostname rules.
    #[serde(rename = "externalURLs", skip_serializing_if = "Option::is_none")]
    pub external_urls: Option<Vec<String>>,
    /// Ingress provides information about external access points (e.g., load balancer ingress) for this resource.
    #[serde(rename = "ingress", skip_serializing_if = "Option::is_none")]
    pub ingress: Option<Vec<models::V1LoadBalancerIngress>>,
    /// Labels holds the labels associated with this networking resource.
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<std::collections::HashMap<String, String>>,
    /// TargetLabels represents labels associated with the target resources that this resource communicates with.
    #[serde(rename = "targetLabels", skip_serializing_if = "Option::is_none")]
    pub target_labels: Option<std::collections::HashMap<String, String>>,
    /// TargetRefs contains references to other resources that this resource interacts with, such as Services or Pods.
    #[serde(rename = "targetRefs", skip_serializing_if = "Option::is_none")]
    pub target_refs: Option<Vec<models::V1alpha1ResourceRef>>,
}

impl V1alpha1ResourceNetworkingInfo {
    /// ResourceNetworkingInfo holds networking-related information for a resource.
    pub fn new() -> V1alpha1ResourceNetworkingInfo {
        V1alpha1ResourceNetworkingInfo {
            external_urls: None,
            ingress: None,
            labels: None,
            target_labels: None,
            target_refs: None,
        }
    }
}

