/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1KustomizeReplica {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<Box<models::IntstrIntOrString>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl V1alpha1KustomizeReplica {
    pub fn new() -> V1alpha1KustomizeReplica {
        V1alpha1KustomizeReplica {
            count: None,
            name: None,
        }
    }
}

