/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1RevisionHistory {
    /// Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.  +protobuf.options.marshal=false +protobuf.as=Timestamp +protobuf.options.(gogoproto.goproto_stringer)=false
    #[serde(rename = "deployStartedAt", skip_serializing_if = "Option::is_none")]
    pub deploy_started_at: Option<String>,
    /// Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.  +protobuf.options.marshal=false +protobuf.as=Timestamp +protobuf.options.(gogoproto.goproto_stringer)=false
    #[serde(rename = "deployedAt", skip_serializing_if = "Option::is_none")]
    pub deployed_at: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "initiatedBy", skip_serializing_if = "Option::is_none")]
    pub initiated_by: Option<Box<models::V1alpha1OperationInitiator>>,
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    #[serde(rename = "revisions", skip_serializing_if = "Option::is_none")]
    pub revisions: Option<Vec<String>>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<models::V1alpha1ApplicationSource>>,
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<models::V1alpha1ApplicationSource>>,
}

impl V1alpha1RevisionHistory {
    pub fn new() -> V1alpha1RevisionHistory {
        V1alpha1RevisionHistory {
            deploy_started_at: None,
            deployed_at: None,
            id: None,
            initiated_by: None,
            revision: None,
            revisions: None,
            source: None,
            sources: None,
        }
    }
}
