/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1PullRequestGeneratorGithub : PullRequestGenerator defines connection info specific to GitHub.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1PullRequestGeneratorGithub {
    /// The GitHub API URL to talk to. If blank, use https://api.github.com/.
    #[serde(rename = "api", skip_serializing_if = "Option::is_none")]
    pub api: Option<String>,
    /// AppSecretName is a reference to a GitHub App repo-creds secret with permission to access pull requests.
    #[serde(rename = "appSecretName", skip_serializing_if = "Option::is_none")]
    pub app_secret_name: Option<String>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<String>>,
    /// GitHub org or user to scan. Required.
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    /// GitHub repo name to scan. Required.
    #[serde(rename = "repo", skip_serializing_if = "Option::is_none")]
    pub repo: Option<String>,
    #[serde(rename = "tokenRef", skip_serializing_if = "Option::is_none")]
    pub token_ref: Option<Box<models::V1alpha1SecretRef>>,
}

impl V1alpha1PullRequestGeneratorGithub {
    /// PullRequestGenerator defines connection info specific to GitHub.
    pub fn new() -> V1alpha1PullRequestGeneratorGithub {
        V1alpha1PullRequestGeneratorGithub {
            api: None,
            app_secret_name: None,
            labels: None,
            owner: None,
            repo: None,
            token_ref: None,
        }
    }
}

