/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1PullRequestGeneratorBitbucketServer : PullRequestGeneratorBitbucketServer defines connection info specific to BitbucketServer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1PullRequestGeneratorBitbucketServer {
    /// The Bitbucket REST API URL to talk to e.g. https://bitbucket.org/rest Required.
    #[serde(rename = "api", skip_serializing_if = "Option::is_none")]
    pub api: Option<String>,
    #[serde(rename = "basicAuth", skip_serializing_if = "Option::is_none")]
    pub basic_auth: Option<Box<models::V1alpha1BasicAuthBitbucketServer>>,
    #[serde(rename = "bearerToken", skip_serializing_if = "Option::is_none")]
    pub bearer_token: Option<Box<models::V1alpha1BearerTokenBitbucket>>,
    #[serde(rename = "caRef", skip_serializing_if = "Option::is_none")]
    pub ca_ref: Option<Box<models::V1alpha1ConfigMapKeyRef>>,
    #[serde(rename = "insecure", skip_serializing_if = "Option::is_none")]
    pub insecure: Option<bool>,
    /// Project to scan. Required.
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// Repo name to scan. Required.
    #[serde(rename = "repo", skip_serializing_if = "Option::is_none")]
    pub repo: Option<String>,
}

impl V1alpha1PullRequestGeneratorBitbucketServer {
    /// PullRequestGeneratorBitbucketServer defines connection info specific to BitbucketServer.
    pub fn new() -> V1alpha1PullRequestGeneratorBitbucketServer {
        V1alpha1PullRequestGeneratorBitbucketServer {
            api: None,
            basic_auth: None,
            bearer_token: None,
            ca_ref: None,
            insecure: None,
            project: None,
            repo: None,
        }
    }
}
