/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ApplicationSetRolloutStep {
    #[serde(rename = "matchExpressions", skip_serializing_if = "Option::is_none")]
    pub match_expressions: Option<Vec<models::V1alpha1ApplicationMatchExpression>>,
    #[serde(rename = "maxUpdate", skip_serializing_if = "Option::is_none")]
    pub max_update: Option<Box<models::IntstrIntOrString>>,
}

impl V1alpha1ApplicationSetRolloutStep {
    pub fn new() -> V1alpha1ApplicationSetRolloutStep {
        V1alpha1ApplicationSetRolloutStep {
            match_expressions: None,
            max_update: None,
        }
    }
}

