/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1SyncStrategy {
    #[serde(rename = "apply", skip_serializing_if = "Option::is_none")]
    pub apply: Option<Box<models::V1alpha1SyncStrategyApply>>,
    #[serde(rename = "hook", skip_serializing_if = "Option::is_none")]
    pub hook: Option<Box<models::V1alpha1SyncStrategyHook>>,
}

impl V1alpha1SyncStrategy {
    pub fn new() -> V1alpha1SyncStrategy {
        V1alpha1SyncStrategy {
            apply: None,
            hook: None,
        }
    }
}
