/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1SyncStatus {
    #[serde(rename = "comparedTo", skip_serializing_if = "Option::is_none")]
    pub compared_to: Option<Box<models::V1alpha1ComparedTo>>,
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    #[serde(rename = "revisions", skip_serializing_if = "Option::is_none")]
    pub revisions: Option<Vec<String>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl V1alpha1SyncStatus {
    pub fn new() -> V1alpha1SyncStatus {
        V1alpha1SyncStatus {
            compared_to: None,
            revision: None,
            revisions: None,
            status: None,
        }
    }
}
