/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1ConfigMapKeyRef : Utility struct for a reference to a configmap key.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ConfigMapKeyRef {
    #[serde(rename = "configMapName", skip_serializing_if = "Option::is_none")]
    pub config_map_name: Option<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl V1alpha1ConfigMapKeyRef {
    /// Utility struct for a reference to a configmap key.
    pub fn new() -> V1alpha1ConfigMapKeyRef {
        V1alpha1ConfigMapKeyRef {
            config_map_name: None,
            key: None,
        }
    }
}
