/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1SyncStrategyHook : SyncStrategyHook will perform a sync using hooks annotations. If no hook annotation is specified falls back to `kubectl apply`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1SyncStrategyHook {
    #[serde(rename = "syncStrategyApply", skip_serializing_if = "Option::is_none")]
    pub sync_strategy_apply: Option<Box<models::V1alpha1SyncStrategyApply>>,
}

impl V1alpha1SyncStrategyHook {
    /// SyncStrategyHook will perform a sync using hooks annotations. If no hook annotation is specified falls back to `kubectl apply`.
    pub fn new() -> V1alpha1SyncStrategyHook {
        V1alpha1SyncStrategyHook {
            sync_strategy_apply: None,
        }
    }
}

