/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1BasicAuthBitbucketServer : BasicAuthBitbucketServer defines the username/(password or personal access token) for Basic auth.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1BasicAuthBitbucketServer {
    #[serde(rename = "passwordRef", skip_serializing_if = "Option::is_none")]
    pub password_ref: Option<Box<models::V1alpha1SecretRef>>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl V1alpha1BasicAuthBitbucketServer {
    /// BasicAuthBitbucketServer defines the username/(password or personal access token) for Basic auth.
    pub fn new() -> V1alpha1BasicAuthBitbucketServer {
        V1alpha1BasicAuthBitbucketServer {
            password_ref: None,
            username: None,
        }
    }
}

