/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ApplicationSetTree {
    #[serde(rename = "nodes", skip_serializing_if = "Option::is_none")]
    pub nodes: Option<Vec<models::V1alpha1ResourceNode>>,
}

impl V1alpha1ApplicationSetTree {
    pub fn new() -> V1alpha1ApplicationSetTree {
        V1alpha1ApplicationSetTree { nodes: None }
    }
}
