/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1RetryStrategy {
    #[serde(rename = "backoff", skip_serializing_if = "Option::is_none")]
    pub backoff: Option<Box<models::V1alpha1Backoff>>,
    /// Limit is the maximum number of attempts for retrying a failed sync. If set to 0, no retries will be performed.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}

impl V1alpha1RetryStrategy {
    pub fn new() -> V1alpha1RetryStrategy {
        V1alpha1RetryStrategy {
            backoff: None,
            limit: None,
        }
    }
}
