/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1GitDirectoryGeneratorItem {
    #[serde(rename = "exclude", skip_serializing_if = "Option::is_none")]
    pub exclude: Option<bool>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

impl V1alpha1GitDirectoryGeneratorItem {
    pub fn new() -> V1alpha1GitDirectoryGeneratorItem {
        V1alpha1GitDirectoryGeneratorItem {
            exclude: None,
            path: None,
        }
    }
}
