/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ExecProviderConfig {
    #[serde(rename = "apiVersion", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<String>>,
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    #[serde(rename = "env", skip_serializing_if = "Option::is_none")]
    pub env: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "installHint", skip_serializing_if = "Option::is_none")]
    pub install_hint: Option<String>,
}

impl V1alpha1ExecProviderConfig {
    pub fn new() -> V1alpha1ExecProviderConfig {
        V1alpha1ExecProviderConfig {
            api_version: None,
            args: None,
            command: None,
            env: None,
            install_hint: None,
        }
    }
}

