/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1ScmProviderGeneratorAwsCodeCommit : SCMProviderGeneratorAWSCodeCommit defines connection info specific to AWS CodeCommit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ScmProviderGeneratorAwsCodeCommit {
    /// Scan all branches instead of just the default branch.
    #[serde(rename = "allBranches", skip_serializing_if = "Option::is_none")]
    pub all_branches: Option<bool>,
    /// Region provides the AWS region to discover repos. if not provided, AppSet controller will infer the current region from environment.
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// Role provides the AWS IAM role to assume, for cross-account repo discovery if not provided, AppSet controller will use its pod/node identity to discover.
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(rename = "tagFilters", skip_serializing_if = "Option::is_none")]
    pub tag_filters: Option<Vec<models::V1alpha1TagFilter>>,
}

impl V1alpha1ScmProviderGeneratorAwsCodeCommit {
    /// SCMProviderGeneratorAWSCodeCommit defines connection info specific to AWS CodeCommit.
    pub fn new() -> V1alpha1ScmProviderGeneratorAwsCodeCommit {
        V1alpha1ScmProviderGeneratorAwsCodeCommit {
            all_branches: None,
            region: None,
            role: None,
            tag_filters: None,
        }
    }
}

