/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ApplicationSource {
    /// Chart is a Helm chart name, and must be specified for applications sourced from a Helm repo.
    #[serde(rename = "chart", skip_serializing_if = "Option::is_none")]
    pub chart: Option<String>,
    #[serde(rename = "directory", skip_serializing_if = "Option::is_none")]
    pub directory: Option<Box<models::V1alpha1ApplicationSourceDirectory>>,
    #[serde(rename = "helm", skip_serializing_if = "Option::is_none")]
    pub helm: Option<Box<models::V1alpha1ApplicationSourceHelm>>,
    #[serde(rename = "kustomize", skip_serializing_if = "Option::is_none")]
    pub kustomize: Option<Box<models::V1alpha1ApplicationSourceKustomize>>,
    /// Name is used to refer to a source and is displayed in the UI. It is used in multi-source Applications.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Path is a directory path within the Git repository, and is only valid for applications sourced from Git.
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "plugin", skip_serializing_if = "Option::is_none")]
    pub plugin: Option<Box<models::V1alpha1ApplicationSourcePlugin>>,
    /// Ref is reference to another source within sources field. This field will not be used if used with a `source` tag.
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    #[serde(rename = "repoURL", skip_serializing_if = "Option::is_none")]
    pub repo_url: Option<String>,
    /// TargetRevision defines the revision of the source to sync the application to. In case of Git, this can be commit, tag, or branch. If omitted, will equal to HEAD. In case of Helm, this is a semver tag for the Chart's version.
    #[serde(rename = "targetRevision", skip_serializing_if = "Option::is_none")]
    pub target_revision: Option<String>,
}

impl V1alpha1ApplicationSource {
    pub fn new() -> V1alpha1ApplicationSource {
        V1alpha1ApplicationSource {
            chart: None,
            directory: None,
            helm: None,
            kustomize: None,
            name: None,
            path: None,
            plugin: None,
            r#ref: None,
            repo_url: None,
            target_revision: None,
        }
    }
}

