/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1RepoCredsList : RepositoryList is a collection of Repositories.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1RepoCredsList {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::V1alpha1RepoCreds>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::V1ListMeta>>,
}

impl V1alpha1RepoCredsList {
    /// RepositoryList is a collection of Repositories.
    pub fn new() -> V1alpha1RepoCredsList {
        V1alpha1RepoCredsList {
            items: None,
            metadata: None,
        }
    }
}
