/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1ResourceAction : ResourceAction represents an individual action that can be performed on a resource. It includes parameters, an optional disabled flag, an icon for display, and a name for the action.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ResourceAction {
    /// Disabled indicates whether the action is disabled.
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    /// DisplayName provides a user-friendly name for the action.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// IconClass specifies the CSS class for the action's icon.
    #[serde(rename = "iconClass", skip_serializing_if = "Option::is_none")]
    pub icon_class: Option<String>,
    /// Name is the name or identifier for the action.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Params contains the parameters required to execute the action.
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Vec<models::V1alpha1ResourceActionParam>>,
}

impl V1alpha1ResourceAction {
    /// ResourceAction represents an individual action that can be performed on a resource. It includes parameters, an optional disabled flag, an icon for display, and a name for the action.
    pub fn new() -> V1alpha1ResourceAction {
        V1alpha1ResourceAction {
            disabled: None,
            display_name: None,
            icon_class: None,
            name: None,
            params: None,
        }
    }
}
