/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1SyncPolicyAutomated {
    #[serde(rename = "allowEmpty", skip_serializing_if = "Option::is_none")]
    pub allow_empty: Option<bool>,
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
    #[serde(rename = "prune", skip_serializing_if = "Option::is_none")]
    pub prune: Option<bool>,
    #[serde(rename = "selfHeal", skip_serializing_if = "Option::is_none")]
    pub self_heal: Option<bool>,
}

impl V1alpha1SyncPolicyAutomated {
    pub fn new() -> V1alpha1SyncPolicyAutomated {
        V1alpha1SyncPolicyAutomated {
            allow_empty: None,
            enable: None,
            prune: None,
            self_heal: None,
        }
    }
}
