/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1ApplicationWatchEvent : ApplicationWatchEvent contains information about application change.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ApplicationWatchEvent {
    #[serde(rename = "application", skip_serializing_if = "Option::is_none")]
    pub application: Option<Box<models::V1alpha1Application>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl V1alpha1ApplicationWatchEvent {
    /// ApplicationWatchEvent contains information about application change.
    pub fn new() -> V1alpha1ApplicationWatchEvent {
        V1alpha1ApplicationWatchEvent {
            application: None,
            r#type: None,
        }
    }
}
