/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ResourceOverride {
    /// Actions defines the set of actions that can be performed on the resource, as a Lua script.
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<String>,
    /// HealthLua contains a Lua script that defines custom health checks for the resource.
    #[serde(rename = "healthLua", skip_serializing_if = "Option::is_none")]
    pub health_lua: Option<String>,
    #[serde(rename = "ignoreDifferences", skip_serializing_if = "Option::is_none")]
    pub ignore_differences: Option<Box<models::V1alpha1OverrideIgnoreDiff>>,
    #[serde(
        rename = "ignoreResourceUpdates",
        skip_serializing_if = "Option::is_none"
    )]
    pub ignore_resource_updates: Option<Box<models::V1alpha1OverrideIgnoreDiff>>,
    /// KnownTypeFields lists fields for which unit conversions should be applied.
    #[serde(rename = "knownTypeFields", skip_serializing_if = "Option::is_none")]
    pub known_type_fields: Option<Vec<models::V1alpha1KnownTypeField>>,
    /// UseOpenLibs indicates whether to use open-source libraries for the resource.
    #[serde(rename = "useOpenLibs", skip_serializing_if = "Option::is_none")]
    pub use_open_libs: Option<bool>,
}

impl V1alpha1ResourceOverride {
    pub fn new() -> V1alpha1ResourceOverride {
        V1alpha1ResourceOverride {
            actions: None,
            health_lua: None,
            ignore_differences: None,
            ignore_resource_updates: None,
            known_type_fields: None,
            use_open_libs: None,
        }
    }
}
