/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1ApplicationSetStrategy : ApplicationSetStrategy configures how generated Applications are updated in sequence.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ApplicationSetStrategy {
    #[serde(rename = "rollingSync", skip_serializing_if = "Option::is_none")]
    pub rolling_sync: Option<Box<models::V1alpha1ApplicationSetRolloutStrategy>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl V1alpha1ApplicationSetStrategy {
    /// ApplicationSetStrategy configures how generated Applications are updated in sequence.
    pub fn new() -> V1alpha1ApplicationSetStrategy {
        V1alpha1ApplicationSetStrategy {
            rolling_sync: None,
            r#type: None,
        }
    }
}

