/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1ScmProviderGeneratorAzureDevOps : SCMProviderGeneratorAzureDevOps defines connection info specific to Azure DevOps.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ScmProviderGeneratorAzureDevOps {
    #[serde(rename = "accessTokenRef", skip_serializing_if = "Option::is_none")]
    pub access_token_ref: Option<Box<models::V1alpha1SecretRef>>,
    /// Scan all branches instead of just the default branch.
    #[serde(rename = "allBranches", skip_serializing_if = "Option::is_none")]
    pub all_branches: Option<bool>,
    /// The URL to Azure DevOps. If blank, use https://dev.azure.com.
    #[serde(rename = "api", skip_serializing_if = "Option::is_none")]
    pub api: Option<String>,
    /// Azure Devops organization. Required. E.g. \"my-organization\".
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<String>,
    /// Azure Devops team project. Required. E.g. \"my-team\".
    #[serde(rename = "teamProject", skip_serializing_if = "Option::is_none")]
    pub team_project: Option<String>,
}

impl V1alpha1ScmProviderGeneratorAzureDevOps {
    /// SCMProviderGeneratorAzureDevOps defines connection info specific to Azure DevOps.
    pub fn new() -> V1alpha1ScmProviderGeneratorAzureDevOps {
        V1alpha1ScmProviderGeneratorAzureDevOps {
            access_token_ref: None,
            all_branches: None,
            api: None,
            organization: None,
            team_project: None,
        }
    }
}

