/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1ApplicationSetSyncPolicy : ApplicationSetSyncPolicy configures how generated Applications will relate to their ApplicationSet.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ApplicationSetSyncPolicy {
    #[serde(rename = "applicationsSync", skip_serializing_if = "Option::is_none")]
    pub applications_sync: Option<String>,
    /// PreserveResourcesOnDeletion will preserve resources on deletion. If PreserveResourcesOnDeletion is set to true, these Applications will not be deleted.
    #[serde(rename = "preserveResourcesOnDeletion", skip_serializing_if = "Option::is_none")]
    pub preserve_resources_on_deletion: Option<bool>,
}

impl V1alpha1ApplicationSetSyncPolicy {
    /// ApplicationSetSyncPolicy configures how generated Applications will relate to their ApplicationSet.
    pub fn new() -> V1alpha1ApplicationSetSyncPolicy {
        V1alpha1ApplicationSetSyncPolicy {
            applications_sync: None,
            preserve_resources_on_deletion: None,
        }
    }
}

