/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ListGenerator {
    #[serde(rename = "elements", skip_serializing_if = "Option::is_none")]
    pub elements: Option<Vec<models::V1Json>>,
    #[serde(rename = "elementsYaml", skip_serializing_if = "Option::is_none")]
    pub elements_yaml: Option<String>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Box<models::V1alpha1ApplicationSetTemplate>>,
}

impl V1alpha1ListGenerator {
    pub fn new() -> V1alpha1ListGenerator {
        V1alpha1ListGenerator {
            elements: None,
            elements_yaml: None,
            template: None,
        }
    }
}

