/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1ApplicationSetNestedGenerator : ApplicationSetNestedGenerator represents a generator nested within a combination-type generator (MatrixGenerator or MergeGenerator).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ApplicationSetNestedGenerator {
    #[serde(rename = "clusterDecisionResource", skip_serializing_if = "Option::is_none")]
    pub cluster_decision_resource: Option<Box<models::V1alpha1DuckTypeGenerator>>,
    #[serde(rename = "clusters", skip_serializing_if = "Option::is_none")]
    pub clusters: Option<Box<models::V1alpha1ClusterGenerator>>,
    #[serde(rename = "git", skip_serializing_if = "Option::is_none")]
    pub git: Option<Box<models::V1alpha1GitGenerator>>,
    #[serde(rename = "list", skip_serializing_if = "Option::is_none")]
    pub list: Option<Box<models::V1alpha1ListGenerator>>,
    #[serde(rename = "matrix", skip_serializing_if = "Option::is_none")]
    pub matrix: Option<Box<models::V1Json>>,
    #[serde(rename = "merge", skip_serializing_if = "Option::is_none")]
    pub merge: Option<Box<models::V1Json>>,
    #[serde(rename = "plugin", skip_serializing_if = "Option::is_none")]
    pub plugin: Option<Box<models::V1alpha1PluginGenerator>>,
    #[serde(rename = "pullRequest", skip_serializing_if = "Option::is_none")]
    pub pull_request: Option<Box<models::V1alpha1PullRequestGenerator>>,
    #[serde(rename = "scmProvider", skip_serializing_if = "Option::is_none")]
    pub scm_provider: Option<Box<models::V1alpha1ScmProviderGenerator>>,
    #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Box<models::V1LabelSelector>>,
}

impl V1alpha1ApplicationSetNestedGenerator {
    /// ApplicationSetNestedGenerator represents a generator nested within a combination-type generator (MatrixGenerator or MergeGenerator).
    pub fn new() -> V1alpha1ApplicationSetNestedGenerator {
        V1alpha1ApplicationSetNestedGenerator {
            cluster_decision_resource: None,
            clusters: None,
            git: None,
            list: None,
            matrix: None,
            merge: None,
            plugin: None,
            pull_request: None,
            scm_provider: None,
            selector: None,
        }
    }
}

