/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1PluginGenerator : PluginGenerator defines connection info specific to Plugin.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1PluginGenerator {
    #[serde(rename = "configMapRef", skip_serializing_if = "Option::is_none")]
    pub config_map_ref: Option<Box<models::V1alpha1PluginConfigMapRef>>,
    #[serde(rename = "input", skip_serializing_if = "Option::is_none")]
    pub input: Option<Box<models::V1alpha1PluginInput>>,
    /// RequeueAfterSeconds determines how long the ApplicationSet controller will wait before reconciling the ApplicationSet again.
    #[serde(
        rename = "requeueAfterSeconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub requeue_after_seconds: Option<i64>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Box<models::V1alpha1ApplicationSetTemplate>>,
    /// Values contains key/value pairs which are passed directly as parameters to the template. These values will not be sent as parameters to the plugin.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<std::collections::HashMap<String, String>>,
}

impl V1alpha1PluginGenerator {
    /// PluginGenerator defines connection info specific to Plugin.
    pub fn new() -> V1alpha1PluginGenerator {
        V1alpha1PluginGenerator {
            config_map_ref: None,
            input: None,
            requeue_after_seconds: None,
            template: None,
            values: None,
        }
    }
}
