/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1BearerTokenBitbucketCloud : BearerTokenBitbucketCloud defines the Bearer token for BitBucket AppToken auth.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1BearerTokenBitbucketCloud {
    #[serde(rename = "tokenRef", skip_serializing_if = "Option::is_none")]
    pub token_ref: Option<Box<models::V1alpha1SecretRef>>,
}

impl V1alpha1BearerTokenBitbucketCloud {
    /// BearerTokenBitbucketCloud defines the Bearer token for BitBucket AppToken auth.
    pub fn new() -> V1alpha1BearerTokenBitbucketCloud {
        V1alpha1BearerTokenBitbucketCloud {
            token_ref: None,
        }
    }
}

