/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ApplicationSetTemplate {
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::V1alpha1ApplicationSetTemplateMeta>>,
    #[serde(rename = "spec", skip_serializing_if = "Option::is_none")]
    pub spec: Option<Box<models::V1alpha1ApplicationSpec>>,
}

impl V1alpha1ApplicationSetTemplate {
    pub fn new() -> V1alpha1ApplicationSetTemplate {
        V1alpha1ApplicationSetTemplate {
            metadata: None,
            spec: None,
        }
    }
}

