/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1ClusterGenerator : ClusterGenerator defines a generator to match against clusters registered with ArgoCD.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ClusterGenerator {
    #[serde(rename = "flatList", skip_serializing_if = "Option::is_none")]
    pub flat_list: Option<bool>,
    #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Box<models::V1LabelSelector>>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Box<models::V1alpha1ApplicationSetTemplate>>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<std::collections::HashMap<String, String>>,
}

impl V1alpha1ClusterGenerator {
    /// ClusterGenerator defines a generator to match against clusters registered with ArgoCD.
    pub fn new() -> V1alpha1ClusterGenerator {
        V1alpha1ClusterGenerator {
            flat_list: None,
            selector: None,
            template: None,
            values: None,
        }
    }
}
