/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1SourceHydrator : SourceHydrator specifies a dry \"don't repeat yourself\" source for manifests, a sync source from which to sync hydrated manifests, and an optional hydrateTo location to act as a \"staging\" aread for hydrated manifests.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1SourceHydrator {
    #[serde(rename = "drySource", skip_serializing_if = "Option::is_none")]
    pub dry_source: Option<Box<models::V1alpha1DrySource>>,
    #[serde(rename = "hydrateTo", skip_serializing_if = "Option::is_none")]
    pub hydrate_to: Option<Box<models::V1alpha1HydrateTo>>,
    #[serde(rename = "syncSource", skip_serializing_if = "Option::is_none")]
    pub sync_source: Option<Box<models::V1alpha1SyncSource>>,
}

impl V1alpha1SourceHydrator {
    /// SourceHydrator specifies a dry \"don't repeat yourself\" source for manifests, a sync source from which to sync hydrated manifests, and an optional hydrateTo location to act as a \"staging\" aread for hydrated manifests.
    pub fn new() -> V1alpha1SourceHydrator {
        V1alpha1SourceHydrator {
            dry_source: None,
            hydrate_to: None,
            sync_source: None,
        }
    }
}

