/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ApplicationSummary {
    /// ExternalURLs holds all external URLs of application child resources.
    #[serde(rename = "externalURLs", skip_serializing_if = "Option::is_none")]
    pub external_urls: Option<Vec<String>>,
    /// Images holds all images of application child resources.
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<String>>,
}

impl V1alpha1ApplicationSummary {
    pub fn new() -> V1alpha1ApplicationSummary {
        V1alpha1ApplicationSummary {
            external_urls: None,
            images: None,
        }
    }
}

