/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1OverrideIgnoreDiff {
    #[serde(rename = "jSONPointers", skip_serializing_if = "Option::is_none")]
    pub j_son_pointers: Option<Vec<String>>,
    #[serde(rename = "jqPathExpressions", skip_serializing_if = "Option::is_none")]
    pub jq_path_expressions: Option<Vec<String>>,
    #[serde(rename = "managedFieldsManagers", skip_serializing_if = "Option::is_none")]
    pub managed_fields_managers: Option<Vec<String>>,
}

impl V1alpha1OverrideIgnoreDiff {
    pub fn new() -> V1alpha1OverrideIgnoreDiff {
        V1alpha1OverrideIgnoreDiff {
            j_son_pointers: None,
            jq_path_expressions: None,
            managed_fields_managers: None,
        }
    }
}

