/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ApplicationDestination {
    /// Name is an alternate way of specifying the target cluster by its symbolic name. This must be set if Server is not set.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// Server specifies the URL of the target cluster's Kubernetes control plane API. This must be set if Name is not set.
    #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
    pub server: Option<String>,
}

impl V1alpha1ApplicationDestination {
    pub fn new() -> V1alpha1ApplicationDestination {
        V1alpha1ApplicationDestination {
            name: None,
            namespace: None,
            server: None,
        }
    }
}
