/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1KustomizeSelector {
    #[serde(rename = "annotationSelector", skip_serializing_if = "Option::is_none")]
    pub annotation_selector: Option<String>,
    #[serde(rename = "labelSelector", skip_serializing_if = "Option::is_none")]
    pub label_selector: Option<String>,
    #[serde(rename = "resId", skip_serializing_if = "Option::is_none")]
    pub res_id: Option<Box<models::V1alpha1KustomizeResId>>,
}

impl V1alpha1KustomizeSelector {
    pub fn new() -> V1alpha1KustomizeSelector {
        V1alpha1KustomizeSelector {
            annotation_selector: None,
            label_selector: None,
            res_id: None,
        }
    }
}

