/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1PullRequestGeneratorBitbucket : PullRequestGeneratorBitbucket defines connection info specific to Bitbucket.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1PullRequestGeneratorBitbucket {
    /// The Bitbucket REST API URL to talk to. If blank, uses https://api.bitbucket.org/2.0.
    #[serde(rename = "api", skip_serializing_if = "Option::is_none")]
    pub api: Option<String>,
    #[serde(rename = "basicAuth", skip_serializing_if = "Option::is_none")]
    pub basic_auth: Option<Box<models::V1alpha1BasicAuthBitbucketServer>>,
    #[serde(rename = "bearerToken", skip_serializing_if = "Option::is_none")]
    pub bearer_token: Option<Box<models::V1alpha1BearerTokenBitbucketCloud>>,
    /// Workspace to scan. Required.
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    /// Repo name to scan. Required.
    #[serde(rename = "repo", skip_serializing_if = "Option::is_none")]
    pub repo: Option<String>,
}

impl V1alpha1PullRequestGeneratorBitbucket {
    /// PullRequestGeneratorBitbucket defines connection info specific to Bitbucket.
    pub fn new() -> V1alpha1PullRequestGeneratorBitbucket {
        V1alpha1PullRequestGeneratorBitbucket {
            api: None,
            basic_auth: None,
            bearer_token: None,
            owner: None,
            repo: None,
        }
    }
}

