/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1KustomizeOptions {
    #[serde(rename = "binaryPath", skip_serializing_if = "Option::is_none")]
    pub binary_path: Option<String>,
    #[serde(rename = "buildOptions", skip_serializing_if = "Option::is_none")]
    pub build_options: Option<String>,
}

impl V1alpha1KustomizeOptions {
    pub fn new() -> V1alpha1KustomizeOptions {
        V1alpha1KustomizeOptions {
            binary_path: None,
            build_options: None,
        }
    }
}

