/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1PullRequestGeneratorFilter : PullRequestGeneratorFilter is a single pull request filter. If multiple filter types are set on a single struct, they will be AND'd together. All filters must pass for a pull request to be included.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1PullRequestGeneratorFilter {
    #[serde(rename = "branchMatch", skip_serializing_if = "Option::is_none")]
    pub branch_match: Option<String>,
    #[serde(rename = "targetBranchMatch", skip_serializing_if = "Option::is_none")]
    pub target_branch_match: Option<String>,
}

impl V1alpha1PullRequestGeneratorFilter {
    /// PullRequestGeneratorFilter is a single pull request filter. If multiple filter types are set on a single struct, they will be AND'd together. All filters must pass for a pull request to be included.
    pub fn new() -> V1alpha1PullRequestGeneratorFilter {
        V1alpha1PullRequestGeneratorFilter {
            branch_match: None,
            target_branch_match: None,
        }
    }
}
