/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1MatrixGenerator : MatrixGenerator generates the cartesian product of two sets of parameters. The parameters are defined by two nested generators.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1MatrixGenerator {
    #[serde(rename = "generators", skip_serializing_if = "Option::is_none")]
    pub generators: Option<Vec<models::V1alpha1ApplicationSetNestedGenerator>>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Box<models::V1alpha1ApplicationSetTemplate>>,
}

impl V1alpha1MatrixGenerator {
    /// MatrixGenerator generates the cartesian product of two sets of parameters. The parameters are defined by two nested generators.
    pub fn new() -> V1alpha1MatrixGenerator {
        V1alpha1MatrixGenerator {
            generators: None,
            template: None,
        }
    }
}

