/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1alpha1ResourceActionParam : ResourceActionParam represents a parameter for a resource action. It includes a name, value, type, and an optional default value for the parameter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ResourceActionParam {
    /// Default is the default value of the parameter, if any.
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<String>,
    /// Name is the name of the parameter.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Type is the type of the parameter (e.g., string, integer).
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Value is the value of the parameter.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl V1alpha1ResourceActionParam {
    /// ResourceActionParam represents a parameter for a resource action. It includes a name, value, type, and an optional default value for the parameter.
    pub fn new() -> V1alpha1ResourceActionParam {
        V1alpha1ResourceActionParam {
            default: None,
            name: None,
            r#type: None,
            value: None,
        }
    }
}
