/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1OrphanedResourcesMonitorSettings {
    #[serde(rename = "ignore", skip_serializing_if = "Option::is_none")]
    pub ignore: Option<Vec<models::V1alpha1OrphanedResourceKey>>,
    #[serde(rename = "warn", skip_serializing_if = "Option::is_none")]
    pub warn: Option<bool>,
}

impl V1alpha1OrphanedResourcesMonitorSettings {
    pub fn new() -> V1alpha1OrphanedResourcesMonitorSettings {
        V1alpha1OrphanedResourcesMonitorSettings {
            ignore: None,
            warn: None,
        }
    }
}

