/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1KustomizeResId {
    #[serde(rename = "gvk", skip_serializing_if = "Option::is_none")]
    pub gvk: Option<Box<models::V1alpha1KustomizeGvk>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

impl V1alpha1KustomizeResId {
    pub fn new() -> V1alpha1KustomizeResId {
        V1alpha1KustomizeResId {
            gvk: None,
            name: None,
            namespace: None,
        }
    }
}

