/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1JsonnetVar {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl V1alpha1JsonnetVar {
    pub fn new() -> V1alpha1JsonnetVar {
        V1alpha1JsonnetVar {
            code: None,
            name: None,
            value: None,
        }
    }
}

