/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1OperationInitiator {
    /// Automated is set to true if operation was initiated automatically by the application controller.
    #[serde(rename = "automated", skip_serializing_if = "Option::is_none")]
    pub automated: Option<bool>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl V1alpha1OperationInitiator {
    pub fn new() -> V1alpha1OperationInitiator {
        V1alpha1OperationInitiator {
            automated: None,
            username: None,
        }
    }
}

