/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1PluginInput {
    /// Parameters contains the information to pass to the plugin. It is a map. The keys must be strings, and the values can be any type.
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<std::collections::HashMap<String, models::V1Json>>,
}

impl V1alpha1PluginInput {
    pub fn new() -> V1alpha1PluginInput {
        V1alpha1PluginInput {
            parameters: None,
        }
    }
}

