/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1ApplicationSetRolloutStrategy {
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<models::V1alpha1ApplicationSetRolloutStep>>,
}

impl V1alpha1ApplicationSetRolloutStrategy {
    pub fn new() -> V1alpha1ApplicationSetRolloutStrategy {
        V1alpha1ApplicationSetRolloutStrategy {
            steps: None,
        }
    }
}

