/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionVersionMessage {
    #[serde(rename = "BuildDate", skip_serializing_if = "Option::is_none")]
    pub build_date: Option<String>,
    #[serde(rename = "Compiler", skip_serializing_if = "Option::is_none")]
    pub compiler: Option<String>,
    #[serde(rename = "ExtraBuildInfo", skip_serializing_if = "Option::is_none")]
    pub extra_build_info: Option<String>,
    #[serde(rename = "GitCommit", skip_serializing_if = "Option::is_none")]
    pub git_commit: Option<String>,
    #[serde(rename = "GitTag", skip_serializing_if = "Option::is_none")]
    pub git_tag: Option<String>,
    #[serde(rename = "GitTreeState", skip_serializing_if = "Option::is_none")]
    pub git_tree_state: Option<String>,
    #[serde(rename = "GoVersion", skip_serializing_if = "Option::is_none")]
    pub go_version: Option<String>,
    #[serde(rename = "HelmVersion", skip_serializing_if = "Option::is_none")]
    pub helm_version: Option<String>,
    #[serde(rename = "JsonnetVersion", skip_serializing_if = "Option::is_none")]
    pub jsonnet_version: Option<String>,
    #[serde(rename = "KubectlVersion", skip_serializing_if = "Option::is_none")]
    pub kubectl_version: Option<String>,
    #[serde(rename = "KustomizeVersion", skip_serializing_if = "Option::is_none")]
    pub kustomize_version: Option<String>,
    #[serde(rename = "Platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(rename = "Version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl VersionVersionMessage {
    pub fn new() -> VersionVersionMessage {
        VersionVersionMessage {
            build_date: None,
            compiler: None,
            extra_build_info: None,
            git_commit: None,
            git_tag: None,
            git_tree_state: None,
            go_version: None,
            helm_version: None,
            jsonnet_version: None,
            kubectl_version: None,
            kustomize_version: None,
            platform: None,
            version: None,
        }
    }
}

